#!/usr/bin/env bash
# This script installs and configures Nginx to serve a page containing Holberton School

apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html

service nginx start
